### ISSUE TITLE
KLDCriterion updateGradInput should be re-ordered?

### ISSUE THREAD

**Issue by dritchie** [RuiShu/cvae#1]
I believe that the line

```
self.gradInput = {dmu2, dlogv2, dmu1, dlogv1}
```

should actually read

```
self.gradInput = {dmu1, dlogv1, dmu2, dlogv2}
```

right? Let me know if I'm missing something.

On a related note: am I correct in observing that the gradients returned by this method are scaled by a factor of 1/2 from their "true" values? (i.e. why there's a `:div(2)` on all the `logv` gradients and not a `:mul(2)` on all the `mu` gradients)

**Comment by RuiShu** [comment]
This original line 

```
self.gradInput = {dmu2, dlogv2, dmu1, dlogv1}
```

is correct. `KLDCriterion:updateOutput(input, target)` is equivalent to computing `KL(target distribution || input distribution)`, which is why I ended up indexing target as `(mu1, logv1)` and input as `(mu2, logv2)`. In retrospect, the KLDCriterion code is in need of refactoring. 

The gradients are not scaled by a factor of 1/2. The division by 2 appears from the derivation: http://stats.stackexchange.com/questions/60680/kl-divergence-between-two-multivariate-gaussians

It so happens that because KLD varies quadratically w.r.t. the mu parameters, computing the gradient w.r.t. the mu parameters introduces a multiplication by 2 that cancels out the division.

**Comment by dritchie** [comment]
Ah, thanks. I was modifying `KLDCriterion` to take a single table of four inputs (works better with how the rest of my code is structured), and I wanted to be totally sure I wasn't screwing up any ordering.

**Comment by RuiShu** [comment]
You may find it useful to look at:
https://github.com/RuiShu/variational-autoencoder/blob/master/nnutils/GmmKLDCriterion.lua
I eliminated unnecessary memory allocation/cloning.

**Comment by dritchie** [comment]
Cool, thanks! And thanks for this code, in general--it's been a very nice reference point :)

**Comment by RuiShu** [comment]
You're welcome :) 
(fyi, the overall layout of the code is much clearer in https://github.com/RuiShu/variational-autoencoder too, imo. The only downside is I have not released the conditional version yet)
